MOCK_SCHEMES = [
    {
        "scheme_id": "pm-kisan",
        "name": "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)",
        "name_ta": "பிரதம மந்திரி கிசான் சம்மான் நிதி (PM-KISAN)",
        "name_hi": "प्रधानमंत्री किसान सम्मान निधि (PM-KISAN)",
        "ministry": "Ministry of Agriculture and Farmers Welfare",
        "benefit_type": "cash_transfer",
        "benefit_amount": 6000,
        "benefit_frequency": "annual",
        "applicable_states": ["All"],
        "gender": "any",
        "caste_categories": ["All"],
        "min_age": 18,
        "max_age": 100,
        "max_income": None,
        "occupation_types": ["farmer"],
        "documents_required": ["Aadhaar Card", "Bank Account Details", "Land Holding Papers"],
        "application_url": "https://pmkisan.gov.in/",
        "application_deadline": None,
        "is_rolling": True,
        "verified_at": "2026-05-28",
        "active": True
    },
    {
        "scheme_id": "ab-pmjay",
        "name": "Ayushman Bharat Pradhan Mantri Jan Arogya Yojana (AB-PMJAY)",
        "name_ta": "ஆயுஷ்மான் பாரத் பிரதம மந்திரி ஜன் ஆரோக்யா யோஜனா (AB-PMJAY)",
        "name_hi": "आयुष्मान भारत प्रधानमंत्री जन आरोग्य योजना (AB-PMJAY)",
        "ministry": "Ministry of Health and Family Welfare",
        "benefit_type": "insurance",
        "benefit_amount": 500000,
        "benefit_frequency": "annual",
        "applicable_states": ["All"],
        "gender": "any",
        "caste_categories": ["All"],
        "min_age": 0,
        "max_age": 100,
        "max_income": None,
        "occupation_types": ["unorganised_worker", "unemployed"],
        "documents_required": ["Aadhaar Card", "Ration Card"],
        "application_url": "https://mera.pmjay.gov.in/",
        "application_deadline": None,
        "is_rolling": True,
        "verified_at": "2026-05-28",
        "active": True
    },
    {
        "scheme_id": "pmay-g",
        "name": "Pradhan Mantri Awas Yojana - Gramin (PMAY-G)",
        "name_ta": "பிரதம மந்திரி ஆவாஸ் யோஜனா - கிராமின் (PMAY-G)",
        "name_hi": "प्रधानमंत्री आवास योजना - ग्रामीण (PMAY-G)",
        "ministry": "Ministry of Rural Development",
        "benefit_type": "housing",
        "benefit_amount": 120000,
        "benefit_frequency": "one-time",
        "applicable_states": ["All"],
        "gender": "any",
        "caste_categories": ["All"],
        "min_age": 18,
        "max_age": 100,
        "max_income": None,
        "occupation_types": ["All"],
        "documents_required": ["Aadhaar Card", "Job Card", "Bank Account Details"],
        "application_url": "https://pmayg.nic.in/",
        "application_deadline": None,
        "is_rolling": True,
        "verified_at": "2026-05-28",
        "active": True
    },
    {
        "scheme_id": "mgnrega",
        "name": "Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)",
        "name_ta": "மகாத்மா காந்தி தேசிய ஊரக வேலை உறுதி சட்டம் (MGNREGA)",
        "name_hi": "महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी अधिनियम (MGNREGA)",
        "ministry": "Ministry of Rural Development",
        "benefit_type": "employment",
        "benefit_amount": None,
        "benefit_frequency": "one-time",
        "applicable_states": ["All"],
        "gender": "any",
        "caste_categories": ["All"],
        "min_age": 18,
        "max_age": 100,
        "max_income": None,
        "occupation_types": ["unemployed", "unorganised_worker"],
        "documents_required": ["Aadhaar Card", "Bank Account Details", "Photograph"],
        "application_url": "https://nrega.nic.in/",
        "application_deadline": None,
        "is_rolling": True,
        "verified_at": "2026-05-28",
        "active": True
    },
    {
        "scheme_id": "ssy",
        "name": "Sukanya Samriddhi Yojana (SSY)",
        "name_ta": "சுகன்யா சம்ரித்தி யோஜனா (SSY)",
        "name_hi": "सुकन्या समृद्धि योजना (SSY)",
        "ministry": "Ministry of Finance",
        "benefit_type": "savings_scheme",
        "benefit_amount": None,
        "benefit_frequency": "one-time",
        "applicable_states": ["All"],
        "gender": "female",
        "caste_categories": ["All"],
        "min_age": 0,
        "max_age": 10,
        "max_income": None,
        "occupation_types": ["All"],
        "documents_required": ["Birth Certificate of Girl Child", "Identity Proof of Parent", "Address Proof"],
        "application_url": "https://www.nsiindia.gov.in/",
        "application_deadline": None,
        "is_rolling": True,
        "verified_at": "2026-05-28",
        "active": True
    },
    {
        "scheme_id": "apy",
        "name": "Atal Pension Yojana (APY)",
        "name_ta": "அடல் பென்ஷன் யோஜனா (APY)",
        "name_hi": "अटल पेंशन योजना (APY)",
        "ministry": "Ministry of Finance",
        "benefit_type": "insurance",
        "benefit_amount": 5000,
        "benefit_frequency": "monthly",
        "applicable_states": ["All"],
        "gender": "any",
        "caste_categories": ["All"],
        "min_age": 18,
        "max_age": 40,
        "max_income": None,
        "occupation_types": ["unorganised_worker", "self_employed"],
        "documents_required": ["Aadhaar Card", "Savings Bank Account"],
        "application_url": "https://www.pfrda.org.in/",
        "application_deadline": None,
        "is_rolling": True,
        "verified_at": "2026-05-28",
        "active": True
    }
]
